### ISSUE TITLE
Move "compiler options" from Backend to Compiler

### ISSUE THREAD

**Issue by virtustron** [ITA-Dnipro/CompilerWebApp#29]
Global steps to do:
- [x] research Backend source code
- [x] research regular expressions for parsing compiler options
- [x] research using file options "whitelist" 
- [x] implement regular  code from Backend to Compiler
] 
- [x] test Compiler with options feature

**Comment by AndriiSerbeniuk** [comment]
All languages related functionality is in the [`languages`](https://github.com/ITA-Dnipro/CompilerWebApp/tree/develop/webapp/src/languages) module, including compiler options parsing and validation. 

I wanted to make some changes there. These are:
- in the [`compiler_flag`](https://github.com/ITA-Dnipro/CompilerWebApp/blob/develop/webapp/src/languages/compiler_flag.rs) module remove `Undefined` enum variant without a value and use `UndefinedFlag("")` instead of it, and also maybe rename `UndefinedFlag` into just `Undefined`. 
```
pub enum CompilerFlag   // Types of flags a compiler may take
{
    // An undefined flag
    Undefined,
    // An undefined flag that stores it's text
    UndefinedFlag(String),
    ...
```
This would also require to change impls for `PartialEq` and `Hash` traits;
- body of the `validate()` function in the [`flags_validator`](https://github.com/ITA-Dnipro/CompilerWebApp/blob/develop/webapp/src/languages/flags_validator.rs) module is inconsistent: I wanted to use `HashSet`'s set operations like `is_superset` and `intersect` to easily validate whitelisted or blacklisted flags, but it didn't work out because they search by hashes, and I needed to do it by values;
- [`static info`](https://github.com/ITA-Dnipro/CompilerWebApp/tree/develop/webapp/src/languages/static_info) module now contains functions (only for c++) that return language info. These should be changed to config files, but it requires changing `LangInfo` structure in the [`lang_info`](https://github.com/ITA-Dnipro/CompilerWebApp/blob/develop/webapp/src/languages/lang_info.rs) module. Or as an option you don't need to write the entire `LangInfo` structure into a file.

These are all I could muster, feel free to ask about anything.
